# Docker image for Vue
# VERSION 1.0.0
# Author: yuanhong
# 基础镜像使用nginx
FROM nginx

# 作者
MAINTAINER yuanhong <1027928543@qq.com>

ADD dist/ /home/yh/env/course-learning-admin/dist/

ADD default.conf /etc/nginx/conf.d/default.conf

